### ISSUE TITLE
If mixin declaration misses colon, the output also misses a semicolon

### ISSUE THREAD

**Issue by rubenlg** [PolymerLabs/css-slam#14]
I'm running css-slam @2.0.1 released today.

If feed the following input (notice the missing colon after mixin1):
```css
button {
  --mixin1 {
    color: red;
  }
  color: blue;
}
```
Output:
`button{--mixin1{color:red;}color:blue;}`

However, if i feed the correct input, with the colon:
```css
button {
  --mixin1: {
    color: red;
  }
  color: blue;
}
```
The output is instead:
`button{--mixin1:{color:red;};color:blue;}`

**Expected behavior**
- The output should be identical in both cases except for the presence of the colon.
- Even if css-slam doesn't introduce the missing colon (see at the end), it should at least keep the colon after the mixin block. Otherwise chrome gives up on parsing the whole CSS rule, and then the code behaves differently in minified and non minified builds.

**Actual behavior**
Currently css-slam copies the broken mixin block over, and if there is no colon, it also fails to use a semicolon to properly separate that garbage from the remaining correct CSS.

**NOTE**: I'd argue that css-slam should not try to fix the block and add the missing colon, because that would make the CSS behave differently between minified and non-minified builds.
